# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
# sphinx:
#   configuration: docs/conf.py

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF
# formats:
#   - pdf

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt

## Tried to use conda; worked for a bit but then failed to work with typehints added
# on the readthedoc build. but works locally. Revert to pip requirements instead
# since anyway it looks like pip install mkdocs is done on top of conda setup.
# conda:
#   environment: docs/environment.yml